export const TOKENS = {
  ClaudeDataDir: Symbol('ClaudeDataDir'),
  Database: Symbol('Database'),
  LocalLlmUrl: Symbol('LocalLlmUrl'),
  AdapterRegistry: Symbol('AdapterRegistry'),
  IndexManager: Symbol('IndexManager'),
  SearchIndex: Symbol('SearchIndex'),
  FreshnessGuard: Symbol('FreshnessGuard'),
  TokenBudgetManager: Symbol('TokenBudgetManager'),
  PaginationManager: Symbol('PaginationManager'),

  LocalLlmClient: Symbol('LocalLlmClient'),
  LlmClient: Symbol('LlmClient'),
  ProjectResolver: Symbol('ProjectResolver'),
  Analyzer: Symbol('Analyzer'),
  ResponseFormatter: Symbol('ResponseFormatter'),
  TurnIndexer: Symbol('TurnIndexer'),
  PhaseClusterer: Symbol('PhaseClusterer'),
  ContextAuditor: Symbol('ContextAuditor'),
  EmbeddingIndexer: Symbol('EmbeddingIndexer'),
  ToolInvocationLogger: Symbol('ToolInvocationLogger'),
  AuditHistoryService: Symbol('AuditHistoryService'),
} as const
