export const TOKENS = {
  ClaudeDataDir: Symbol('ClaudeDataDir'),
  Database: Symbol('Database'),
  HttpClient: Symbol('HttpClient'),
  LocalLlmUrl: Symbol('LocalLlmUrl'),
  LocalLlmModel: Symbol('LocalLlmModel'),
  SessionAdapter: Symbol('SessionAdapter'),
  AdapterRegistry: Symbol('AdapterRegistry'),
  IndexManager: Symbol('IndexManager'),
  SearchIndex: Symbol('SearchIndex'),
  FreshnessGuard: Symbol('FreshnessGuard'),
  TokenBudgetManager: Symbol('TokenBudgetManager'),
  PaginationManager: Symbol('PaginationManager'),

  LocalLlmClient: Symbol('LocalLlmClient'),
  ProjectResolver: Symbol('ProjectResolver'),
  Analyzer: Symbol('Analyzer'),
  ResponseFormatter: Symbol('ResponseFormatter'),
  TurnIndexer: Symbol('TurnIndexer'),
} as const
